import { Geist, Geist_Mono } from "next/font/google";
import Footer from "@/components/footer/footer.jsx"
import "bootstrap-icons/font/bootstrap-icons.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"

/**
 * @param {{ children: React.ReactNode }} props
 */

export default function Layout({ children }) {
  return (
    <html>
      <body>

        <SidebarProvider>
          <AppSidebar />
          <div className="flex flex-col">

            <main>
              
              {children}
            </main>
            <Footer></Footer>
          </div>
        </SidebarProvider>
      </body>
    </html>
  )
}